# Generated by Django 3.1.6 on 2021-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='foods/')),
            ],
        ),
    ]
