# Generated by Django 3.1.6 on 2021-02-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.CharField(max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='time',
            field=models.IntegerField(default=0, verbose_name='زمان لازم'),
        ),
    ]
