# Generated by Django 3.1.6 on 2021-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20210223_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('D', 'نوشیدنی'), ('DI', 'شام'), ('L', 'ناهار')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
